config/routes.rb
Cookbook::Application.routes.draw do
 resources :books, :recipes, :ingredients
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id
  belongs_to :book_id
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredients)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
    <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
    <%= f.label :chef %>
  <%= f.text_field :chef %>
    <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <% Recipe.all.each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
  <% end %>

  <br>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render :partial => 'form' %>

app/views/books/index.html.erb
<ol>
<% @books.each do |book| %>
  <li>
    <ul>
      <li><%= link_to(book.title, book) %></li>
        <li><%= book.cuisine %></li>
        <li><%= book.chef %></li>
        <li><%= image_tag(book.image) %></li>
        <li><%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure you want to delete this book?') %></li>
        <li><%= link_to('Edit Book', edit_book_path(book)) %></li>

      </ul>
    </li>
<% end %>
</ol

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render :partial => 'form' %>

app/views/books/show.html.erb
<div id="book_info">
  <li><%= link_to(@book.title, @book) %></li>
  <li><%= @book.cuisine %></li>
  <li><%= @book.chef %></li>
  <li><%= image_tag(@book.image) %></li>
  <li><%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure you want to delete this book?') %></li>
</div>

<br>

<% @book.recipes.each do |recipe| %>
  <div class="dish clearfix">
    <div class="recipe">
      <%= recipe.name %>
      <%= image_tag(recipe.image) %>
    </div>

    <% recipe.ingredients.each do |ingredient| %>
      <div class="ingredients">
        <ul>
        <li><%= ingredient.name %></li>
        <li><%= image_tag(ingredient.image) %></li>
        </ul>
      </div>


  <% end %>
  </div>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
    <%= f.label :measurement %>
  <%= f.text_field :measurement %>
    <%= f.label :cost %>
  <%= f.text_field :cost %>
    <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<ol>
<% @ingredients.each do |ingredient| %>
  <li>
    <ul>
      <li><%= link_to(ingredient.name, ingredient) %></li>
        <li><%= ingredient.measurement %></li>
        <li><%= ingredient.cost %></li>
        <li><%= image_tag(ingredient.image) %></li>
        <li><%= link_to('Delete Ingredient', @ingredient, :method => :delete, :confirm => 'Are you sure you want to delete this ingredient?') %></li>
        <li><%= link_to('Edit Ingredient', edit_ingredient_path(ingredient)) %></li>
        <br>

      </ul>
    </li>
<% end %>
</ol

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<div class="ingredients">
  <ul>
    <li><%= @ingredient.name %></li>
    <li><%= @ingredient.measurement %></li>
    <li><%= @ingredient.cost %></li>
    <li><%= image_tag(@ingredient.image) %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to("Books", books_path) %>
    <%= link_to("Recipes", recipes_path) %>
    <%= link_to("Ingredients", ingredients_path ) %>
    <%= link_to("New Book", new_book_path) %>
    <%= link_to("New Recipe", new_recipe_path) %>
    <%= link_to("New Ingredient", new_ingredient_path) %>
  </nav>

<%= yield %>

</body>
</html>